// import "~/styles/globals.css";

// import { GeistSans } from "geist/font/sans";
// import { type Metadata } from "next";

// import { TRPCReactProvider } from "~/trpc/react";
// import { ThemeProvider } from './ThemeProvider';
// import { ClientProvider } from "./_components/ClientProvider";
// //import { SessionProvider } from "next-auth/react";
// //import SessionProvider from "./_components/SessionProvider";
// import SessionProvider from "next-auth/react";
// import CredentialsProvider from 'next-auth/providers/credentials'


// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" className={`${GeistSans.variable}`}>
//       <body>
//         <ClientProvider>
//           <ThemeProvider>
//             <TRPCReactProvider>{children}</TRPCReactProvider>
//           </ThemeProvider>
//         </ClientProvider>
//       </body>
//     </html>
//   );
// }
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { Providers } from "./_components/ClientProvider";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-white dark:bg-lyra-dark text-black dark:text-white">
        <Providers>
          <TRPCReactProvider>
            {children}
          </TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}

